name: Test
on: [push]
jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run Action
      uses: ./
      with:
        project-id: 1
        src-column-id: 2
        dest-column-id: 3
